### PR TITLE
PLUGIN-318: Integration Tests for formats in PubSubSource and PubSubSink 

### PR DESCRIPTION
**Pull request by flakrimjusufi**
PR: https://github.com/data-integrations/google-cloud/pull/437
JIRA Ticket: https://cdap.atlassian.net/browse/PLUGIN-318

### CODE REVIEW

**Review by rmstar — COMMENTED** [review]
https://github.com/data-integrations/google-cloud/pull/530 has been merged. Can you please update the PR to enable tests that were failing because of PLUGIN-575?

**Comment by flakrimjusufi** [comment]
> [data-integrations/google-cloud#530](https://github.com/data-integrations/google-cloud/pull/530) has been merged. Can you please update the PR to enable tests that were failing because of PLUGIN-575?

PR Updated.

**Review by rmstar — COMMENTED** [review]
couple of questions:
1. Why do we have 2 functions pubSubToPubSubByte and publisherTestFormat that seem to be almost identical. Can we avoid duplicating code?
2. Can we add tests for different input and output formats. For example, json -> parquet, avro -> text etc.

**Comment by flakrimjusufi** [comment]
> couple of questions:
> 
> 1. Why do we have 2 functions pubSubToPubSubByte and publisherTestFormat that seem to be almost identical. Can we avoid duplicating code?
> 2. Can we add tests for different input and output formats. For example, json -> parquet, avro -> text etc.

Please check the updated PR. 

I've done a re-factoring of the functions and avoided duplicate code. 
More formats such as Json to Parquet, Json to Avro, Avro to Text were added.

**Review by rmstar — APPROVED** [review]
lgtm, please squash commits

**Comment by flakrimjusufi** [comment]
> lgtm, please squash commits

Commits squashed.

**Pull request merged**
